# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 80, 541, 168))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_input = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.password_input = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 111, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 111, 51))
        self.label_2.setObjectName("label_2")
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(510, 250, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.submit_btn.setFont(font)
        self.submit_btn.setObjectName("submit_btn")
        self.display_area = QtWidgets.QTextBrowser(self.centralwidget)
        self.display_area.setGeometry(QtCore.QRect(70, 390, 511, 61))
        self.display_area.setObjectName("display_area")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menua = QtWidgets.QMenu(self.menu)
        self.menua.setObjectName("menua")
        self.menuaa = QtWidgets.QMenu(self.menua)
        self.menuaa.setObjectName("menuaa")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.actionbb = QtWidgets.QAction(MainWindow)
        self.actionbb.setObjectName("actionbb")
        self.menua.addAction(self.menuaa.menuAction())
        self.menua.addAction(self.actionbb)
        self.menu.addAction(self.menua.menuAction())
        self.menu.addAction(self.actionb)
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">用户名</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">密    码</span></p></body></html>"))
        self.submit_btn.setText(_translate("MainWindow", "提交"))
        self.menu.setTitle(_translate("MainWindow", "测试一下"))
        self.menua.setTitle(_translate("MainWindow", "a"))
        self.menuaa.setTitle(_translate("MainWindow", "aa"))
        self.actionb.setText(_translate("MainWindow", "b"))
        self.exit.setText(_translate("MainWindow", "exit"))
        self.actionbb.setText(_translate("MainWindow", "bb"))
